### PR TITLE
Update to latest dependencies

### PR DESCRIPTION
**Pull request by avsm**
From the CHANGES file in this patch series: 
- Support the latest GitHub and Atd bindings (>=2.0.0) (@avsm)
- Support the Uri 2.0.0+ API (@avsm)
- Port build to Dune from Jbuilder (@avsm). 
- Remove use of deprecated Tyxml `pcdata` function in favour of `txt` (@avsm)
- Add watermarking of versions in the build system (@avsm)
- Remove topkg build targets in favour of using `dune-release` (@avsm)

### CODE REVIEW

**Comment by avsm** [comment]
I think I need your help with the CI @djs55 ... no idea what the circleci upgrade warnings are all about.  This PR does need opam2, and it looks like the containers being used are opam1

**Comment by djs55** [comment]
It looks like a macOS / Xcode version clash:
```
carthage: A full installation of Xcode.app 9.4 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode 9.4 cannot be installed on macOS 10.12.
You must upgrade your version of macOS.
```
...
oh
...
is this still using the EOL circle.yml v1? I think this needs updating to v2. I can take a look.

**Comment by avsm** [comment]
yeah, it looks like its still using EOL CircleCI v1. Let me know if I can help, otherwise I'll leave this PR to you to merge -- I can do the release.

**Comment by djs55** [comment]
I've force-pushed a rebase to latest master which should at least fix the CircleCI issue. Let's see what's left to fix.

**Comment by avsm** [comment]
This is still using opam1 in the Dockerfile CI, so I've pushed some changes to build newer Dockerfiles and also upgraded opam 2.0 metadata to pass lint

**Comment by avsm** [comment]
It's gone green now; I can cut a release with this if you can approve the merge @djs55

**Comment by avsm** [comment]
Although note that CircleCI is testing with 4.05 and the Linux containers are 4.07.1, in case that matters

**Pull request merged**
