### PR TITLE
Initial commit of C# bindings

### PR DESCRIPTION
**Pull request by dave-tucker**
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>

### CODE REVIEW

**Comment by talex5** [comment]
What is `paket.bootstrapper.exe`?

**Comment by dave-tucker** [comment]
https://fsprojects.github.io/Paket/bootstrapper.html

It's used to handle the dependency management for the C Sharp code

**Comment by samoht** [comment]
Thanks for your contribution, that looks nice (although I am not sure I will be able to review your C# code fully :-)

Can you rebase your PR into master where I fixed the issue on CircleCI. Also, could you describe which level of confidence you have for these bindings, which tests you wrote/did etc, that will help click on the green button (although I would appreciate if a C# expert would review it first, @dgageot or @simonferquel maybe?).

**Comment by dgageot** [comment]
@samoht please let Simon and I review this PR before you merge. Your feedback is more than welcome of course!

**Comment by dgageot** [comment]
ping @simonferquel

**Comment by dave-tucker** [comment]
ping @dgageot @simonferquel did either of you get a chance to review this?

**Comment by samoht** [comment]
ping @dgageot and @simonferquel

**Comment by dave-tucker** [comment]
Closing due to lack of activity

**Pull request closed without merging**
