### PR TITLE
Re-add `make depends`

### PR DESCRIPTION
**Pull request by samoht**
/cc @talex5

### CODE REVIEW

**Comment by samoht** [comment]
Fix https://github.com/moby/datakit/issues/537

**Comment by talex5** [comment]
`Error: Findlib package "github-hooks.unix" not found.`

Maybe `datakit` needs pinning too? But then:
```
datakit needs to be installed.
The following dependencies couldn't be met:
  - datakit -> irmin >= 1.1.0
  - datakit -> irmin-git >= 1.0.0 -> irmin < 1.1.0 -> git (<= 1.1.0 | = 1.2.0) -> conduit = 0.5.1 -> sexplib < 113.01.00
  - datakit -> irmin-git >= 1.0.0 -> irmin < 1.1.0 -> git (<= 1.1.0 | = 1.2.0) -> comparelib -> type_conv < 112.02.00
Your request can't be satisfied:
  - Conflicting version constraints for irmin
```

**Comment by talex5** [comment]
Ah, needs `opam pin add irmin-git.1.1.0 --dev` too.

**Comment by talex5** [comment]
Also, `datakit-bridge-github.opam` needs pinning.

**Comment by samoht** [comment]
Hum yes, it would probably be better to pin all the packages... I'll push a fix.

For irmin-git.1.1.0 it's in the process of being released: https://github.com/ocaml/opam-repository/pull/9041

**Comment by talex5** [comment]
And `datakit-bridge-local-git`, but:
```
The following dependencies couldn't be met:
  - datakit-bridge-local-git -> irmin-unix >= 1.1.0
Your request can't be satisfied:
  - No package matches irmin-unix>=1.1.0.
```
Fixed by:
```
opam pin add irmin-unix.1.1.0 -n https://github.com/mirage/irmin.git#89196ad17c53b02f333022a87ecc264ec8c06af0
```

**Comment by samoht** [comment]
irmin-unix is also in the process of being released: https://github.com/ocaml/opam-repository/pull/9040

**Comment by talex5** [comment]
It works!! 4.9s :-)

**Pull request merged**
